import {
  safetyTrainingAPI,
  surgicalProcedureAPI,
  customerServiceAPI,
  vrEnvironmentAPI,
  incidentReportAPI,
  assessmentQuestionAPI,
  assessmentScoreAPI,
  complianceAPI,
  trainingModuleAPI,
  certificationAPI,
} from '../services/api';

export const FEATURES = [
  {
    key: 'safety-training',
    name: 'Safety Training Scenarios',
    shortName: 'Safety Training',
    description: 'Create and manage VR safety training scenarios for various industries and hazard types.',
    icon: '\u26A0\uFE0F',
    color: '#ef4444',
    bgColor: 'rgba(239, 68, 68, 0.1)',
    isAI: true,
    api: safetyTrainingAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'hazardType', label: 'Hazard Type' },
      { key: 'industry', label: 'Industry' },
      { key: 'difficulty', label: 'Difficulty', type: 'difficulty' },
      { key: 'duration', label: 'Duration', suffix: ' min' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'hazardType', label: 'Hazard Type', type: 'select', options: ['Fall Hazard', 'Chemical Hazard', 'Electrical Hazard', 'Fire Hazard', 'Biological Hazard', 'Mechanical Hazard', 'Confined Space', 'Ergonomic Hazard', 'Radiation Hazard', 'Noise Hazard'] },
      { key: 'industry', label: 'Industry', type: 'select', options: ['Construction', 'Manufacturing', 'Healthcare', 'Oil & Gas', 'Mining', 'Energy', 'Office', 'Transportation', 'Warehousing'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'vrEnvironment', label: 'VR Environment', type: 'text' },
      { key: 'duration', label: 'Duration (min)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'archived'] },
    ],
    generateFields: [
      { key: 'industry', label: 'Industry', type: 'select', options: ['Construction', 'Manufacturing', 'Healthcare', 'Oil & Gas', 'Mining', 'Office'] },
      { key: 'hazardType', label: 'Hazard Type', type: 'select', options: ['Fall Hazard', 'Chemical Hazard', 'Electrical Hazard', 'Fire Hazard', 'Biological Hazard'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'objectives', label: 'Learning Objectives', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'hazardType', label: 'Hazard Type' },
          { key: 'industry', label: 'Industry' },
          { key: 'difficulty', label: 'Difficulty' },
          { key: 'vrEnvironment', label: 'VR Environment' },
          { key: 'duration', label: 'Duration', suffix: ' minutes' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'surgical-procedures',
    name: 'Surgical Procedure Practice',
    shortName: 'Surgical Procedures',
    description: 'Design and manage VR surgical procedure training simulations with step-by-step guidance.',
    icon: '\uD83C\uDFE5',
    color: '#0ea5e9',
    bgColor: 'rgba(14, 165, 233, 0.1)',
    isAI: true,
    api: surgicalProcedureAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'procedureType', label: 'Type' },
      { key: 'specialty', label: 'Specialty' },
      { key: 'complexity', label: 'Complexity', type: 'difficulty' },
      { key: 'duration', label: 'Duration', suffix: ' min' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'procedureType', label: 'Procedure Type', type: 'select', options: ['Open', 'Laparoscopic', 'Arthroscopic', 'Robotic', 'Endoscopic', 'Microsurgery', 'Minimally Invasive'] },
      { key: 'specialty', label: 'Specialty', type: 'select', options: ['General Surgery', 'Orthopedics', 'Cardiothoracic Surgery', 'Neurosurgery', 'Ophthalmology', 'ENT Surgery', 'Urology', 'Obstetrics', 'Spine Surgery'] },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'duration', label: 'Duration (min)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'archived'] },
    ],
    generateFields: [
      { key: 'specialty', label: 'Specialty', type: 'select', options: ['General Surgery', 'Orthopedics', 'Cardiothoracic Surgery', 'Neurosurgery', 'ENT Surgery'] },
      { key: 'procedureType', label: 'Type', type: 'select', options: ['Open', 'Laparoscopic', 'Arthroscopic', 'Robotic', 'Endoscopic'] },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'steps', label: 'Procedure Steps', type: 'steps' },
      { key: 'equipment', label: 'Required Equipment', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'procedureType', label: 'Procedure Type' },
          { key: 'specialty', label: 'Specialty' },
          { key: 'complexity', label: 'Complexity' },
          { key: 'duration', label: 'Duration', suffix: ' minutes' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'customer-service',
    name: 'Customer Service Simulation',
    shortName: 'Customer Service',
    description: 'Build realistic customer service roleplay scenarios for VR-based training programs.',
    icon: '\uD83D\uDDE3\uFE0F',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    isAI: true,
    api: customerServiceAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'scenarioType', label: 'Type' },
      { key: 'industry', label: 'Industry' },
      { key: 'difficulty', label: 'Difficulty', type: 'difficulty' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'scenarioType', label: 'Scenario Type', type: 'select', options: ['Complaint Handling', 'Billing Issue', 'Technical Support', 'Service Recovery', 'Retention', 'Emergency Support', 'Product Issue', 'Information Request'] },
      { key: 'industry', label: 'Industry', type: 'select', options: ['Retail', 'Telecommunications', 'Banking', 'Airlines', 'Hospitality', 'Healthcare', 'Insurance', 'E-commerce', 'Food Service'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'customerPersona', label: 'Customer Persona', type: 'text' },
      { key: 'issue', label: 'Issue', type: 'textarea' },
      { key: 'resolution', label: 'Resolution', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'archived'] },
    ],
    generateFields: [
      { key: 'industry', label: 'Industry', type: 'select', options: ['Retail', 'Telecommunications', 'Banking', 'Airlines', 'Hospitality', 'Healthcare'] },
      { key: 'scenarioType', label: 'Type', type: 'select', options: ['Complaint Handling', 'Billing Issue', 'Technical Support', 'Service Recovery'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'issue', label: 'Customer Issue', type: 'text' },
      { key: 'resolution', label: 'Recommended Resolution', type: 'text' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'scenarioType', label: 'Scenario Type' },
          { key: 'industry', label: 'Industry' },
          { key: 'difficulty', label: 'Difficulty' },
          { key: 'customerPersona', label: 'Customer Persona' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'vr-environments',
    name: 'VR Environment Templates',
    shortName: 'VR Environments',
    description: 'Design and manage virtual reality environment templates for training simulations.',
    icon: '\uD83C\uDF0D',
    color: '#8b5cf6',
    bgColor: 'rgba(139, 92, 246, 0.1)',
    isAI: true,
    api: vrEnvironmentAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'environmentType', label: 'Type' },
      { key: 'setting', label: 'Setting' },
      { key: 'complexity', label: 'Complexity', type: 'difficulty' },
      { key: 'polyCount', label: 'Poly Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'environmentType', label: 'Environment Type', type: 'select', options: ['Industrial', 'Medical', 'Commercial', 'Construction', 'Laboratory', 'Mining', 'Transportation', 'Education', 'Food Service', 'Oil & Gas'] },
      { key: 'setting', label: 'Setting', type: 'select', options: ['Indoor', 'Outdoor', 'Underground', 'Offshore'] },
      { key: 'lighting', label: 'Lighting', type: 'text' },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['low', 'medium', 'high'] },
      { key: 'polyCount', label: 'Polygon Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'archived'] },
    ],
    generateFields: [
      { key: 'environmentType', label: 'Type', type: 'select', options: ['Industrial', 'Medical', 'Commercial', 'Construction', 'Laboratory'] },
      { key: 'setting', label: 'Setting', type: 'select', options: ['Indoor', 'Outdoor', 'Underground', 'Offshore'] },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['low', 'medium', 'high'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'interactiveElements', label: 'Interactive Elements', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'environmentType', label: 'Environment Type' },
          { key: 'setting', label: 'Setting' },
          { key: 'lighting', label: 'Lighting' },
          { key: 'complexity', label: 'Complexity' },
          { key: 'polyCount', label: 'Polygon Count' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'incident-reports',
    name: 'Incident Report Analysis',
    shortName: 'Incident Reports',
    description: 'Analyze and manage workplace incident reports with AI-powered root cause analysis.',
    icon: '\uD83D\uDCCB',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.1)',
    isAI: true,
    api: incidentReportAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'incidentType', label: 'Type' },
      { key: 'severity', label: 'Severity', type: 'severity' },
      { key: 'location', label: 'Location' },
      { key: 'date', label: 'Date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'incidentType', label: 'Incident Type', type: 'select', options: ['Slip/Fall', 'Chemical Exposure', 'Near Miss', 'Electrical', 'Ergonomic', 'Fire', 'Vehicle', 'Machine Related', 'Confined Space', 'Biological', 'Structural Failure', 'Falling Object'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'moderate', 'high', 'critical'] },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'rootCause', label: 'Root Cause', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'investigating', 'resolved', 'closed'] },
    ],
    generateFields: [
      { key: 'incidentType', label: 'Type', type: 'select', options: ['Slip/Fall', 'Chemical Exposure', 'Electrical', 'Fire', 'Machine Related'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'moderate', 'high', 'critical'] },
      { key: 'industry', label: 'Industry', type: 'select', options: ['Construction', 'Manufacturing', 'Healthcare', 'Warehousing', 'Office'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'rootCause', label: 'Root Cause Analysis', type: 'text' },
      { key: 'correctiveActions', label: 'Corrective Actions', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'incidentType', label: 'Incident Type' },
          { key: 'severity', label: 'Severity' },
          { key: 'location', label: 'Location' },
          { key: 'date', label: 'Date' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'assessment-questions',
    name: 'Assessment Question Generator',
    shortName: 'Assessment Questions',
    description: 'Generate and manage assessment questions for training evaluations using AI.',
    icon: '\u2753',
    color: '#ec4899',
    bgColor: 'rgba(236, 72, 153, 0.1)',
    isAI: true,
    api: assessmentQuestionAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'questionType', label: 'Type' },
      { key: 'category', label: 'Category' },
      { key: 'difficulty', label: 'Difficulty', type: 'difficulty' },
      { key: 'points', label: 'Points' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'question', label: 'Question', type: 'textarea', required: true },
      { key: 'questionType', label: 'Question Type', type: 'select', options: ['multiple-choice', 'true-false', 'short-answer'] },
      { key: 'category', label: 'Category', type: 'select', options: ['Safety', 'Fire Safety', 'Chemical Safety', 'Surgical Safety', 'Customer Service', 'VR Design', 'Emergency Response', 'Compliance', 'Ergonomics', 'VR Technology'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'correctAnswer', label: 'Correct Answer', type: 'text' },
      { key: 'explanation', label: 'Explanation', type: 'textarea' },
      { key: 'points', label: 'Points', type: 'number' },
    ],
    generateFields: [
      { key: 'category', label: 'Category', type: 'select', options: ['Safety', 'Fire Safety', 'Surgical Safety', 'Customer Service', 'Emergency Response'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'questionType', label: 'Type', type: 'select', options: ['multiple-choice', 'true-false', 'short-answer'] },
    ],
    detailSections: [
      { key: 'question', label: 'Question', type: 'text' },
      { key: 'options', label: 'Answer Options', type: 'tags' },
      { key: 'explanation', label: 'Explanation', type: 'text' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'questionType', label: 'Question Type' },
          { key: 'category', label: 'Category' },
          { key: 'difficulty', label: 'Difficulty' },
          { key: 'correctAnswer', label: 'Correct Answer' },
          { key: 'points', label: 'Points' },
        ]
      },
    ],
  },
  {
    key: 'assessment-scores',
    name: 'Assessment Scoring',
    shortName: 'Assessment Scores',
    description: 'Track and manage trainee assessment scores and performance metrics.',
    icon: '\uD83D\uDCCA',
    color: '#06b6d4',
    bgColor: 'rgba(6, 182, 212, 0.1)',
    isAI: false,
    api: assessmentScoreAPI,
    columns: [
      { key: 'traineeName', label: 'Trainee' },
      { key: 'moduleName', label: 'Module' },
      { key: 'score', label: 'Score' },
      { key: 'percentage', label: 'Percentage', suffix: '%' },
      { key: 'passed', label: 'Passed', type: 'boolean' },
      { key: 'attemptDate', label: 'Date', type: 'date' },
    ],
    formFields: [
      { key: 'traineeName', label: 'Trainee Name', type: 'text', required: true },
      { key: 'traineeEmail', label: 'Trainee Email', type: 'email', required: true },
      { key: 'moduleName', label: 'Module Name', type: 'text', required: true },
      { key: 'score', label: 'Score', type: 'number', required: true },
      { key: 'maxScore', label: 'Max Score', type: 'number', required: true },
      { key: 'percentage', label: 'Percentage', type: 'number' },
      { key: 'timeSpent', label: 'Time Spent (seconds)', type: 'number' },
      { key: 'passed', label: 'Passed', type: 'select', options: ['true', 'false'] },
      { key: 'feedback', label: 'Feedback', type: 'textarea' },
    ],
    detailSections: [
      { key: 'feedback', label: 'Feedback', type: 'text' },
      {
        label: 'Score Details', type: 'grid', fields: [
          { key: 'traineeName', label: 'Trainee Name' },
          { key: 'traineeEmail', label: 'Trainee Email' },
          { key: 'moduleName', label: 'Module' },
          { key: 'score', label: 'Score' },
          { key: 'maxScore', label: 'Max Score' },
          { key: 'percentage', label: 'Percentage', suffix: '%' },
          { key: 'passed', label: 'Passed' },
          { key: 'timeSpent', label: 'Time Spent', suffix: 's' },
        ]
      },
    ],
  },
  {
    key: 'compliance',
    name: 'Compliance Tracking',
    shortName: 'Compliance',
    description: 'Track regulatory compliance requirements, audits, and deadlines.',
    icon: '\u2705',
    color: '#059669',
    bgColor: 'rgba(5, 150, 105, 0.1)',
    isAI: false,
    api: complianceAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'regulationType', label: 'Type' },
      { key: 'authority', label: 'Authority' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'expiryDate', label: 'Expiry Date' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'regulationType', label: 'Regulation Type', type: 'select', options: ['Federal', 'State', 'National', 'International', 'Industry', 'Accreditation'] },
      { key: 'authority', label: 'Authority', type: 'text' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'expired', 'archived'] },
      { key: 'lastAuditDate', label: 'Last Audit Date', type: 'date' },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'applicableDepartments', label: 'Applicable Departments', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'regulationType', label: 'Regulation Type' },
          { key: 'authority', label: 'Authority' },
          { key: 'effectiveDate', label: 'Effective Date' },
          { key: 'expiryDate', label: 'Expiry Date' },
          { key: 'priority', label: 'Priority' },
          { key: 'status', label: 'Status' },
          { key: 'lastAuditDate', label: 'Last Audit Date' },
        ]
      },
    ],
  },
  {
    key: 'training-modules',
    name: 'Training Modules',
    shortName: 'Training Modules',
    description: 'Manage training modules, curricula, and learning programs.',
    icon: '\uD83D\uDCDA',
    color: '#6366f1',
    bgColor: 'rgba(99, 102, 241, 0.1)',
    isAI: false,
    api: trainingModuleAPI,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'difficulty', label: 'Difficulty', type: 'difficulty' },
      { key: 'duration', label: 'Duration', suffix: ' min' },
      { key: 'format', label: 'Format' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['Safety', 'Fire Safety', 'Medical', 'Customer Service', 'Technical', 'Emergency Response', 'Leadership', 'Health', 'Compliance'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'duration', label: 'Duration (min)', type: 'number' },
      { key: 'format', label: 'Format', type: 'select', options: ['VR Interactive', 'VR Simulation', 'VR Roleplay', 'VR Hands-on', 'Hands-on Lab', 'Blended Learning', 'Workshop'] },
      { key: 'maxParticipants', label: 'Max Participants', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'archived'] },
    ],
    detailSections: [
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'learningObjectives', label: 'Learning Objectives', type: 'tags' },
      { key: 'prerequisites', label: 'Prerequisites', type: 'tags' },
      {
        label: 'Details', type: 'grid', fields: [
          { key: 'category', label: 'Category' },
          { key: 'difficulty', label: 'Difficulty' },
          { key: 'duration', label: 'Duration', suffix: ' minutes' },
          { key: 'format', label: 'Format' },
          { key: 'maxParticipants', label: 'Max Participants' },
          { key: 'status', label: 'Status' },
        ]
      },
    ],
  },
  {
    key: 'certifications',
    name: 'Certification Management',
    shortName: 'Certifications',
    description: 'Track trainee certifications, expiration dates, and renewal requirements.',
    icon: '\uD83C\uDFC5',
    color: '#d97706',
    bgColor: 'rgba(217, 119, 6, 0.1)',
    isAI: false,
    api: certificationAPI,
    columns: [
      { key: 'traineeName', label: 'Trainee' },
      { key: 'certificationName', label: 'Certification' },
      { key: 'issuingBody', label: 'Issuing Body' },
      { key: 'issueDate', label: 'Issue Date' },
      { key: 'expiryDate', label: 'Expiry Date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'traineeName', label: 'Trainee Name', type: 'text', required: true },
      { key: 'traineeEmail', label: 'Trainee Email', type: 'email', required: true },
      { key: 'certificationName', label: 'Certification Name', type: 'text', required: true },
      { key: 'issuingBody', label: 'Issuing Body', type: 'text' },
      { key: 'issueDate', label: 'Issue Date', type: 'date' },
      { key: 'expiryDate', label: 'Expiry Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'revoked', 'pending'] },
      { key: 'score', label: 'Score', type: 'number' },
      { key: 'certificateNumber', label: 'Certificate Number', type: 'text' },
      { key: 'renewalRequired', label: 'Renewal Required', type: 'select', options: ['true', 'false'] },
    ],
    detailSections: [
      {
        label: 'Certification Details', type: 'grid', fields: [
          { key: 'traineeName', label: 'Trainee Name' },
          { key: 'traineeEmail', label: 'Trainee Email' },
          { key: 'certificationName', label: 'Certification' },
          { key: 'issuingBody', label: 'Issuing Body' },
          { key: 'issueDate', label: 'Issue Date' },
          { key: 'expiryDate', label: 'Expiry Date' },
          { key: 'status', label: 'Status' },
          { key: 'score', label: 'Score' },
          { key: 'certificateNumber', label: 'Certificate Number' },
          { key: 'renewalRequired', label: 'Renewal Required' },
        ]
      },
    ],
  },
];

export function getFeature(key) {
  return FEATURES.find(f => f.key === key);
}
