const bcrypt = require('bcryptjs');
const {
  sequelize,
  User,
  SafetyTrainingScenario,
  SurgicalProcedure,
  CustomerServiceSimulation,
  VREnvironmentTemplate,
  IncidentReport,
  AssessmentQuestion,
  AssessmentScore,
  ComplianceRequirement,
  TrainingModule,
  CertificationRecord,
} = require('../models');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database synced.');

    // Seed User
    const hashedPassword = await bcrypt.hash('password123', 10);
    await User.create({
      email: 'admin@vrtraining.com',
      password: hashedPassword,
      firstName: 'Admin',
      lastName: 'User',
      role: 'admin',
    });
    console.log('User seeded.');

    // 1. Safety Training Scenarios (15)
    await SafetyTrainingScenario.bulkCreate([
      { title: 'Construction Fall Prevention', description: 'Training scenario for preventing falls at construction sites including scaffolding, ladders, and roof work safety protocols.', hazardType: 'Fall Hazard', industry: 'Construction', difficulty: 'intermediate', vrEnvironment: 'Multi-story construction site', objectives: ['Identify fall hazards', 'Proper harness usage', 'Guardrail inspection', 'Emergency response'], duration: 45, status: 'active', aiGenerated: false },
      { title: 'Chemical Spill Response', description: 'Emergency response procedures for handling chemical spills in a laboratory environment with various hazardous materials.', hazardType: 'Chemical Hazard', industry: 'Manufacturing', difficulty: 'advanced', vrEnvironment: 'Industrial chemistry lab', objectives: ['Identify chemical types', 'Proper PPE selection', 'Containment procedures', 'Decontamination steps'], duration: 60, status: 'active', aiGenerated: false },
      { title: 'Electrical Safety Basics', description: 'Fundamental electrical safety training covering lockout/tagout procedures, arc flash prevention, and safe work practices.', hazardType: 'Electrical Hazard', industry: 'Energy', difficulty: 'beginner', vrEnvironment: 'Electrical substation', objectives: ['Lockout/tagout procedures', 'Arc flash awareness', 'Safe distance protocols', 'Emergency shutdown'], duration: 30, status: 'active', aiGenerated: false },
      { title: 'Confined Space Entry', description: 'Safe procedures for entering and working in confined spaces including tanks, vessels, and underground vaults.', hazardType: 'Confined Space', industry: 'Oil & Gas', difficulty: 'advanced', vrEnvironment: 'Industrial tank farm', objectives: ['Atmospheric testing', 'Entry permit procedures', 'Rescue planning', 'Communication protocols'], duration: 50, status: 'active', aiGenerated: false },
      { title: 'Fire Evacuation Drill', description: 'Office building fire evacuation training including alarm response, exit routes, and assembly point procedures.', hazardType: 'Fire Hazard', industry: 'Office', difficulty: 'beginner', vrEnvironment: 'Multi-floor office building', objectives: ['Alarm recognition', 'Evacuation routes', 'Assembly procedures', 'Headcount verification'], duration: 20, status: 'active', aiGenerated: false },
      { title: 'Forklift Operation Safety', description: 'Comprehensive forklift safety training covering pre-operation inspection, load handling, and pedestrian awareness.', hazardType: 'Vehicle Hazard', industry: 'Warehousing', difficulty: 'intermediate', vrEnvironment: 'Large warehouse facility', objectives: ['Pre-trip inspection', 'Load capacity limits', 'Pedestrian safety zones', 'Parking procedures'], duration: 40, status: 'active', aiGenerated: false },
      { title: 'Healthcare Bloodborne Pathogens', description: 'Training on preventing exposure to bloodborne pathogens in healthcare settings including proper handling and disposal.', hazardType: 'Biological Hazard', industry: 'Healthcare', difficulty: 'intermediate', vrEnvironment: 'Hospital emergency room', objectives: ['Universal precautions', 'Sharps handling', 'Exposure response', 'Proper disposal'], duration: 35, status: 'active', aiGenerated: false },
      { title: 'Noise Exposure Prevention', description: 'Industrial noise hazard awareness and hearing conservation program training for manufacturing environments.', hazardType: 'Noise Hazard', industry: 'Manufacturing', difficulty: 'beginner', vrEnvironment: 'Manufacturing plant floor', objectives: ['Noise level assessment', 'Hearing protection selection', 'Audiometric testing awareness', 'Engineering controls'], duration: 25, status: 'active', aiGenerated: false },
      { title: 'Excavation and Trenching Safety', description: 'Safety procedures for excavation work including soil classification, shoring requirements, and cave-in prevention.', hazardType: 'Excavation Hazard', industry: 'Construction', difficulty: 'advanced', vrEnvironment: 'Active excavation site', objectives: ['Soil classification', 'Protective systems', 'Competent person duties', 'Emergency rescue'], duration: 55, status: 'active', aiGenerated: false },
      { title: 'Ergonomic Workstation Setup', description: 'Proper workstation ergonomics training to prevent repetitive strain injuries and musculoskeletal disorders.', hazardType: 'Ergonomic Hazard', industry: 'Office', difficulty: 'beginner', vrEnvironment: 'Modern office space', objectives: ['Chair adjustment', 'Monitor positioning', 'Keyboard placement', 'Break scheduling'], duration: 20, status: 'active', aiGenerated: false },
      { title: 'Radiation Safety Protocol', description: 'Radiation safety procedures for medical imaging departments including ALARA principles and shielding techniques.', hazardType: 'Radiation Hazard', industry: 'Healthcare', difficulty: 'advanced', vrEnvironment: 'Radiology department', objectives: ['ALARA principles', 'Dosimeter usage', 'Shielding techniques', 'Emergency procedures'], duration: 45, status: 'active', aiGenerated: false },
      { title: 'Hot Work Permit Procedures', description: 'Safety training for welding, cutting, and other hot work operations including fire watch and permit requirements.', hazardType: 'Fire Hazard', industry: 'Manufacturing', difficulty: 'intermediate', vrEnvironment: 'Industrial welding shop', objectives: ['Permit requirements', 'Fire watch duties', 'Ventilation needs', 'PPE selection'], duration: 40, status: 'active', aiGenerated: false },
      { title: 'Hazardous Material Transportation', description: 'DOT regulations and safety procedures for transporting hazardous materials by road including placarding and documentation.', hazardType: 'Transportation Hazard', industry: 'Transportation', difficulty: 'intermediate', vrEnvironment: 'Loading dock and highway', objectives: ['DOT classifications', 'Placarding requirements', 'Shipping papers', 'Emergency response'], duration: 50, status: 'active', aiGenerated: false },
      { title: 'Machine Guarding Essentials', description: 'Training on proper machine guarding techniques, safeguarding devices, and preventing caught-in/between injuries.', hazardType: 'Mechanical Hazard', industry: 'Manufacturing', difficulty: 'intermediate', vrEnvironment: 'Production line facility', objectives: ['Guard types identification', 'Safeguarding devices', 'Point of operation hazards', 'Maintenance procedures'], duration: 35, status: 'active', aiGenerated: false },
      { title: 'Mining Underground Safety', description: 'Underground mining safety training covering ground support, ventilation, and emergency evacuation procedures.', hazardType: 'Mining Hazard', industry: 'Mining', difficulty: 'advanced', vrEnvironment: 'Underground mine tunnel', objectives: ['Ground support inspection', 'Ventilation monitoring', 'Self-rescue devices', 'Emergency communication'], duration: 60, status: 'active', aiGenerated: false },
    ]);
    console.log('Safety Training Scenarios seeded.');

    // 2. Surgical Procedures (15)
    await SurgicalProcedure.bulkCreate([
      { title: 'Laparoscopic Cholecystectomy', description: 'Minimally invasive removal of the gallbladder using laparoscopic instruments and camera guidance.', procedureType: 'Laparoscopic', specialty: 'General Surgery', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Patient positioning', details: 'Supine position with reverse Trendelenburg' }, { stepNumber: 2, action: 'Port placement', details: 'Insert four trocars at designated sites' }, { stepNumber: 3, action: 'Critical view of safety', details: 'Identify cystic duct and artery' }, { stepNumber: 4, action: 'Clip and divide', details: 'Apply clips to cystic duct and artery' }, { stepNumber: 5, action: 'Gallbladder dissection', details: 'Remove gallbladder from liver bed' }], equipment: ['Laparoscope', 'Trocars', 'Clip applier', 'Electrocautery', 'Endoscopic bag'], duration: 60, status: 'active', aiGenerated: false },
      { title: 'Total Knee Replacement', description: 'Complete replacement of the knee joint with prosthetic components for severe arthritis cases.', procedureType: 'Open', specialty: 'Orthopedics', complexity: 'advanced', steps: [{ stepNumber: 1, action: 'Incision', details: 'Midline anterior approach' }, { stepNumber: 2, action: 'Bone preparation', details: 'Cut femoral and tibial surfaces' }, { stepNumber: 3, action: 'Trial components', details: 'Test fit prosthetic components' }, { stepNumber: 4, action: 'Cementing', details: 'Apply bone cement and final components' }, { stepNumber: 5, action: 'Closure', details: 'Layer-by-layer wound closure' }], equipment: ['Oscillating saw', 'Alignment guides', 'Prosthetic components', 'Bone cement', 'Retractors'], duration: 120, status: 'active', aiGenerated: false },
      { title: 'Appendectomy', description: 'Surgical removal of the appendix, typically performed as an emergency procedure for acute appendicitis.', procedureType: 'Laparoscopic', specialty: 'General Surgery', complexity: 'beginner', steps: [{ stepNumber: 1, action: 'Port placement', details: 'Three-port technique' }, { stepNumber: 2, action: 'Identification', details: 'Locate appendix at cecum' }, { stepNumber: 3, action: 'Mesoappendix division', details: 'Divide blood supply' }, { stepNumber: 4, action: 'Base ligation', details: 'Staple or loop-ligate base' }, { stepNumber: 5, action: 'Extraction', details: 'Remove through port site' }], equipment: ['Laparoscope', 'Endoloop', 'Graspers', 'Stapler', 'Specimen bag'], duration: 45, status: 'active', aiGenerated: false },
      { title: 'Coronary Artery Bypass Graft', description: 'Open heart surgery to restore blood flow using grafted vessels to bypass blocked coronary arteries.', procedureType: 'Open', specialty: 'Cardiothoracic Surgery', complexity: 'advanced', steps: [{ stepNumber: 1, action: 'Sternotomy', details: 'Median sternotomy incision' }, { stepNumber: 2, action: 'Harvesting', details: 'Harvest saphenous vein or internal mammary artery' }, { stepNumber: 3, action: 'Cardiopulmonary bypass', details: 'Initiate heart-lung machine' }, { stepNumber: 4, action: 'Anastomosis', details: 'Sew graft vessels to coronary arteries' }, { stepNumber: 5, action: 'Weaning', details: 'Wean from bypass and close chest' }], equipment: ['Sternal saw', 'Cardiopulmonary bypass machine', 'Sutures', 'Retractors', 'Hemostats'], duration: 240, status: 'active', aiGenerated: false },
      { title: 'Cataract Surgery - Phacoemulsification', description: 'Ultrasonic removal of a clouded lens and replacement with an artificial intraocular lens.', procedureType: 'Microsurgery', specialty: 'Ophthalmology', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Corneal incision', details: 'Create small self-sealing incision' }, { stepNumber: 2, action: 'Capsulorrhexis', details: 'Create circular opening in lens capsule' }, { stepNumber: 3, action: 'Phacoemulsification', details: 'Fragment and aspirate lens material' }, { stepNumber: 4, action: 'IOL insertion', details: 'Fold and insert intraocular lens' }, { stepNumber: 5, action: 'Wound check', details: 'Verify watertight closure' }], equipment: ['Phaco machine', 'Operating microscope', 'IOL injector', 'Keratome', 'Viscoelastic'], duration: 30, status: 'active', aiGenerated: false },
      { title: 'Cesarean Section', description: 'Surgical delivery of a baby through an incision in the mother abdomen and uterus.', procedureType: 'Open', specialty: 'Obstetrics', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Pfannenstiel incision', details: 'Low transverse abdominal incision' }, { stepNumber: 2, action: 'Uterine incision', details: 'Low transverse uterine incision' }, { stepNumber: 3, action: 'Delivery', details: 'Deliver infant and placenta' }, { stepNumber: 4, action: 'Uterine closure', details: 'Close uterus in two layers' }, { stepNumber: 5, action: 'Abdominal closure', details: 'Close fascia and skin' }], equipment: ['Scalpel', 'Retractors', 'Sutures', 'Clamps', 'Suction'], duration: 45, status: 'active', aiGenerated: false },
      { title: 'Arthroscopic ACL Reconstruction', description: 'Minimally invasive reconstruction of the anterior cruciate ligament using autograft or allograft tendon.', procedureType: 'Arthroscopic', specialty: 'Orthopedics', complexity: 'advanced', steps: [{ stepNumber: 1, action: 'Diagnostic arthroscopy', details: 'Assess joint and confirm ACL tear' }, { stepNumber: 2, action: 'Graft harvest', details: 'Harvest patellar or hamstring tendon' }, { stepNumber: 3, action: 'Tunnel drilling', details: 'Create femoral and tibial tunnels' }, { stepNumber: 4, action: 'Graft passage', details: 'Thread graft through tunnels' }, { stepNumber: 5, action: 'Fixation', details: 'Secure graft with screws or buttons' }], equipment: ['Arthroscope', 'Drill guide', 'Interference screws', 'Graft preparation board', 'Shaver'], duration: 90, status: 'active', aiGenerated: false },
      { title: 'Thyroidectomy', description: 'Partial or total removal of the thyroid gland for thyroid cancer, goiter, or hyperthyroidism.', procedureType: 'Open', specialty: 'ENT Surgery', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Collar incision', details: 'Transverse cervical incision' }, { stepNumber: 2, action: 'Strap muscles', details: 'Divide or retract strap muscles' }, { stepNumber: 3, action: 'Vessel ligation', details: 'Identify and ligate thyroid vessels' }, { stepNumber: 4, action: 'Nerve identification', details: 'Identify recurrent laryngeal nerve' }, { stepNumber: 5, action: 'Gland removal', details: 'Dissect and remove thyroid tissue' }], equipment: ['Nerve monitor', 'Energy device', 'Retractors', 'Sutures', 'Hemostats'], duration: 90, status: 'active', aiGenerated: false },
      { title: 'Lumbar Discectomy', description: 'Surgical removal of herniated disc material pressing on spinal nerves in the lumbar spine.', procedureType: 'Minimally Invasive', specialty: 'Neurosurgery', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Positioning', details: 'Prone on Wilson frame' }, { stepNumber: 2, action: 'Localization', details: 'Fluoroscopic level confirmation' }, { stepNumber: 3, action: 'Laminotomy', details: 'Remove small portion of lamina' }, { stepNumber: 4, action: 'Disc removal', details: 'Remove herniated disc fragment' }, { stepNumber: 5, action: 'Closure', details: 'Close fascia and skin' }], equipment: ['Operating microscope', 'Kerrison rongeurs', 'Pituitary rongeurs', 'Fluoroscopy', 'Retractors'], duration: 60, status: 'active', aiGenerated: false },
      { title: 'Hernia Repair - Lichtenstein', description: 'Open tension-free mesh repair of an inguinal hernia using the Lichtenstein technique.', procedureType: 'Open', specialty: 'General Surgery', complexity: 'beginner', steps: [{ stepNumber: 1, action: 'Inguinal incision', details: 'Incision along inguinal ligament' }, { stepNumber: 2, action: 'Sac identification', details: 'Identify and reduce hernia sac' }, { stepNumber: 3, action: 'Mesh placement', details: 'Place polypropylene mesh' }, { stepNumber: 4, action: 'Mesh fixation', details: 'Suture mesh to inguinal ligament and conjoint tendon' }, { stepNumber: 5, action: 'Closure', details: 'Close external oblique and skin' }], equipment: ['Mesh', 'Sutures', 'Retractors', 'Electrocautery', 'Scissors'], duration: 45, status: 'active', aiGenerated: false },
      { title: 'Endoscopic Sinus Surgery', description: 'Minimally invasive surgery to treat chronic sinusitis by opening blocked sinus passages.', procedureType: 'Endoscopic', specialty: 'ENT Surgery', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Nasal preparation', details: 'Decongest and anesthetize nasal mucosa' }, { stepNumber: 2, action: 'Uncinectomy', details: 'Remove uncinate process' }, { stepNumber: 3, action: 'Maxillary antrostomy', details: 'Open maxillary sinus ostium' }, { stepNumber: 4, action: 'Ethmoidectomy', details: 'Open ethmoid air cells' }, { stepNumber: 5, action: 'Hemostasis', details: 'Control bleeding and place packing' }], equipment: ['Endoscope', 'Microdebrider', 'Through-cutting instruments', 'Suction', 'Image guidance system'], duration: 60, status: 'active', aiGenerated: false },
      { title: 'Hip Hemiarthroplasty', description: 'Partial hip replacement where only the femoral head is replaced, typically for femoral neck fractures.', procedureType: 'Open', specialty: 'Orthopedics', complexity: 'intermediate', steps: [{ stepNumber: 1, action: 'Approach', details: 'Posterior or anterolateral approach' }, { stepNumber: 2, action: 'Dislocation', details: 'Dislocate femoral head' }, { stepNumber: 3, action: 'Femoral preparation', details: 'Ream and broach femoral canal' }, { stepNumber: 4, action: 'Prosthesis insertion', details: 'Insert femoral component' }, { stepNumber: 5, action: 'Reduction', details: 'Reduce hip and test stability' }], equipment: ['Femoral broaches', 'Prosthesis', 'Cement (if cemented)', 'Retractors', 'Saw'], duration: 75, status: 'active', aiGenerated: false },
      { title: 'Tonsillectomy', description: 'Surgical removal of the palatine tonsils for recurrent tonsillitis or obstructive sleep apnea.', procedureType: 'Open', specialty: 'ENT Surgery', complexity: 'beginner', steps: [{ stepNumber: 1, action: 'Mouth gag', details: 'Insert Crowe-Davis mouth gag' }, { stepNumber: 2, action: 'Tonsil retraction', details: 'Grasp and retract tonsil medially' }, { stepNumber: 3, action: 'Dissection', details: 'Dissect tonsil from tonsillar fossa' }, { stepNumber: 4, action: 'Hemostasis', details: 'Cauterize or suture bleeding points' }, { stepNumber: 5, action: 'Inspection', details: 'Inspect fossa for residual bleeding' }], equipment: ['Mouth gag', 'Tonsil forceps', 'Electrocautery', 'Suction', 'Adenoid curette'], duration: 30, status: 'active', aiGenerated: false },
      { title: 'Robotic Prostatectomy', description: 'Robot-assisted laparoscopic radical prostatectomy for prostate cancer treatment.', procedureType: 'Robotic', specialty: 'Urology', complexity: 'advanced', steps: [{ stepNumber: 1, action: 'Port placement', details: 'Place six ports for robotic arms' }, { stepNumber: 2, action: 'Bladder neck division', details: 'Divide bladder neck from prostate' }, { stepNumber: 3, action: 'Nerve sparing', details: 'Preserve neurovascular bundles' }, { stepNumber: 4, action: 'Apex division', details: 'Divide urethra at prostatic apex' }, { stepNumber: 5, action: 'Anastomosis', details: 'Reconnect bladder to urethra' }], equipment: ['Da Vinci robot', 'Trocars', 'Bipolar forceps', 'Needle driver', 'Specimen bag'], duration: 180, status: 'active', aiGenerated: false },
      { title: 'Spinal Fusion - PLIF', description: 'Posterior lumbar interbody fusion for degenerative disc disease or spondylolisthesis.', procedureType: 'Open', specialty: 'Spine Surgery', complexity: 'advanced', steps: [{ stepNumber: 1, action: 'Exposure', details: 'Posterior midline approach with subperiosteal dissection' }, { stepNumber: 2, action: 'Decompression', details: 'Laminectomy and facetectomy' }, { stepNumber: 3, action: 'Disc preparation', details: 'Remove disc material and prepare endplates' }, { stepNumber: 4, action: 'Cage insertion', details: 'Insert interbody cage with graft' }, { stepNumber: 5, action: 'Pedicle screws', details: 'Place pedicle screws and rods' }], equipment: ['Pedicle screw system', 'Interbody cages', 'High-speed drill', 'Fluoroscopy', 'Bone graft'], duration: 180, status: 'active', aiGenerated: false },
    ]);
    console.log('Surgical Procedures seeded.');

    // 3. Customer Service Simulations (15)
    await CustomerServiceSimulation.bulkCreate([
      { title: 'Angry Customer Return', description: 'Handle an irate customer demanding a refund for a product outside the return window.', scenarioType: 'Complaint Handling', industry: 'Retail', difficulty: 'intermediate', customerPersona: 'Frustrated middle-aged professional', issue: 'Customer purchased electronics 45 days ago and wants a full refund due to product malfunction', resolution: 'Offer repair service, extended warranty, or store credit as alternatives to full refund', status: 'active', aiGenerated: false },
      { title: 'Billing Dispute Resolution', description: 'Resolve a complex billing dispute where the customer was charged incorrectly on multiple occasions.', scenarioType: 'Billing Issue', industry: 'Telecommunications', difficulty: 'advanced', customerPersona: 'Detail-oriented senior customer', issue: 'Customer has been overcharged for three consecutive months due to a system error', resolution: 'Issue full credit for overcharges, apply service discount, and escalate system bug to technical team', status: 'active', aiGenerated: false },
      { title: 'Technical Support Walkthrough', description: 'Guide a non-technical customer through troubleshooting their home internet connection.', scenarioType: 'Technical Support', industry: 'Internet Service', difficulty: 'beginner', customerPersona: 'Elderly customer with limited tech knowledge', issue: 'Home internet is not working after a power outage', resolution: 'Walk through router restart, check cable connections, and verify network settings step by step', status: 'active', aiGenerated: false },
      { title: 'Hotel Overbooking Crisis', description: 'Manage a guest who arrives to find their reserved room is not available due to overbooking.', scenarioType: 'Service Recovery', industry: 'Hospitality', difficulty: 'advanced', customerPersona: 'Business traveler on tight schedule', issue: 'Confirmed reservation not honored due to hotel overbooking during peak season', resolution: 'Arrange comparable or upgraded accommodation at nearby property, cover transportation, offer future stay discount', status: 'active', aiGenerated: false },
      { title: 'Insurance Claim Denial', description: 'Explain a claim denial to a distressed policyholder and explore alternative options.', scenarioType: 'Complaint Handling', industry: 'Insurance', difficulty: 'advanced', customerPersona: 'Anxious homeowner after weather damage', issue: 'Home damage claim denied due to policy exclusion for flood damage', resolution: 'Explain exclusion clearly, help file appeal if applicable, discuss supplemental flood insurance options', status: 'active', aiGenerated: false },
      { title: 'Restaurant Food Allergy Complaint', description: 'Handle a serious complaint about allergen presence in food despite customer notifying staff.', scenarioType: 'Safety Complaint', industry: 'Food Service', difficulty: 'advanced', customerPersona: 'Parent of child with severe allergy', issue: 'Child had allergic reaction to dish that was supposed to be nut-free', resolution: 'Ensure immediate medical attention, document incident, comp meal, implement kitchen protocol review', status: 'active', aiGenerated: false },
      { title: 'Delayed Flight Passenger', description: 'Assist a passenger whose connecting flight is affected by a weather-related delay.', scenarioType: 'Service Recovery', industry: 'Airlines', difficulty: 'intermediate', customerPersona: 'Business traveler missing important meeting', issue: 'Flight delayed 4 hours causing missed connection and business meeting', resolution: 'Rebook on next available flight, provide lounge access, issue travel voucher, help contact meeting participants', status: 'active', aiGenerated: false },
      { title: 'Subscription Cancellation Save', description: 'Retain a long-term customer who wants to cancel their premium subscription service.', scenarioType: 'Retention', industry: 'Streaming Service', difficulty: 'intermediate', customerPersona: 'Budget-conscious young professional', issue: 'Customer wants to cancel due to recent price increase feeling the service is no longer worth the cost', resolution: 'Offer loyalty discount, highlight new content, suggest downgrade to cheaper tier, provide pause option', status: 'active', aiGenerated: false },
      { title: 'Defective Product Exchange', description: 'Process an exchange for a defective product while maintaining customer satisfaction.', scenarioType: 'Product Issue', industry: 'Electronics', difficulty: 'beginner', customerPersona: 'Tech-savvy young customer', issue: 'Laptop purchased last week has a dead pixel cluster on the display', resolution: 'Apologize, offer immediate exchange or refund, expedite replacement shipping, add extended warranty free', status: 'active', aiGenerated: false },
      { title: 'Medical Office Wait Time', description: 'Address a patient frustrated with excessive wait time at a medical office.', scenarioType: 'Complaint Handling', industry: 'Healthcare', difficulty: 'intermediate', customerPersona: 'Working parent with limited time', issue: 'Patient has waited over an hour past their appointment time with no communication from staff', resolution: 'Apologize sincerely, explain reason for delay, offer to reschedule with priority, waive copay for inconvenience', status: 'active', aiGenerated: false },
      { title: 'Banking Fraud Alert', description: 'Help a panicked customer who received a fraud alert on their account.', scenarioType: 'Emergency Support', industry: 'Banking', difficulty: 'advanced', customerPersona: 'Senior citizen unfamiliar with digital banking', issue: 'Multiple unauthorized transactions detected on debit card totaling $2,500', resolution: 'Freeze card immediately, document fraudulent transactions, initiate dispute, issue temporary card, set up alerts', status: 'active', aiGenerated: false },
      { title: 'Gym Membership Dispute', description: 'Handle a member who disputes being charged after they believe they cancelled their membership.', scenarioType: 'Billing Issue', industry: 'Fitness', difficulty: 'beginner', customerPersona: 'College student on tight budget', issue: 'Charged for three months after verbally requesting cancellation which was not processed', resolution: 'Process cancellation immediately, refund disputed charges, offer to restart at discounted rate if interested', status: 'active', aiGenerated: false },
      { title: 'Car Dealership Service Complaint', description: 'Address a customer unhappy with the quality of service performed on their vehicle.', scenarioType: 'Service Quality', industry: 'Automotive', difficulty: 'intermediate', customerPersona: 'Meticulous car enthusiast', issue: 'Vehicle returned from service with dashboard warning light still on and new scratch on bumper', resolution: 'Document damage with photos, schedule priority rework at no charge, arrange courtesy vehicle, escalate scratch repair', status: 'active', aiGenerated: false },
      { title: 'Online Order Wrong Item', description: 'Resolve a situation where a customer received completely wrong items in their online order.', scenarioType: 'Order Issue', industry: 'E-commerce', difficulty: 'beginner', customerPersona: 'First-time online shopper', issue: 'Received winter boots instead of the summer sandals ordered for an upcoming vacation in 3 days', resolution: 'Ship correct item with overnight delivery free of charge, provide return label for wrong item, apply discount code', status: 'active', aiGenerated: false },
      { title: 'Utility Rate Increase Inquiry', description: 'Explain a rate increase to a concerned long-term residential customer.', scenarioType: 'Information Request', industry: 'Utilities', difficulty: 'intermediate', customerPersona: 'Fixed-income retiree', issue: 'Monthly utility bill increased by 25% with no apparent change in usage', resolution: 'Explain rate structure changes, review usage patterns, suggest energy audit, enroll in budget billing program', status: 'active', aiGenerated: false },
    ]);
    console.log('Customer Service Simulations seeded.');

    // 4. VR Environment Templates (15)
    await VREnvironmentTemplate.bulkCreate([
      { title: 'Industrial Factory Floor', description: 'A realistic factory floor with operating machinery, conveyor belts, and safety zones for industrial safety training.', environmentType: 'Industrial', setting: 'Indoor', lighting: 'Fluorescent overhead with task lighting', interactiveElements: ['Emergency stop buttons', 'Fire extinguishers', 'Safety barriers', 'PPE stations', 'Machinery controls'], complexity: 'high', polyCount: 2500000, status: 'active', aiGenerated: false },
      { title: 'Hospital Operating Room', description: 'Fully equipped sterile operating room with surgical instruments, monitors, and anesthesia equipment.', environmentType: 'Medical', setting: 'Indoor', lighting: 'Surgical lights with ambient ceiling lights', interactiveElements: ['Surgical instruments', 'Patient monitors', 'Anesthesia machine', 'Scrub station', 'Supply cabinets'], complexity: 'high', polyCount: 3000000, status: 'active', aiGenerated: false },
      { title: 'Office Building Multi-Floor', description: 'Modern multi-story office building with cubicles, meeting rooms, break room, and fire exits for evacuation training.', environmentType: 'Commercial', setting: 'Indoor', lighting: 'Natural and fluorescent mixed', interactiveElements: ['Fire alarms', 'Emergency exits', 'Elevators', 'Stairwells', 'Fire extinguishers'], complexity: 'medium', polyCount: 1800000, status: 'active', aiGenerated: false },
      { title: 'Construction Site High-Rise', description: 'Active high-rise construction site with scaffolding, cranes, and multiple work zones at various heights.', environmentType: 'Construction', setting: 'Outdoor', lighting: 'Natural daylight with shadows', interactiveElements: ['Scaffolding', 'Safety harnesses', 'Crane controls', 'Tool stations', 'Warning signs'], complexity: 'high', polyCount: 2800000, status: 'active', aiGenerated: false },
      { title: 'Retail Store Front', description: 'Modern retail store with checkout counters, shelving units, back office, and customer service desk.', environmentType: 'Commercial', setting: 'Indoor', lighting: 'Bright commercial lighting', interactiveElements: ['POS terminals', 'Product displays', 'Customer service desk', 'Storage room', 'Security cameras'], complexity: 'medium', polyCount: 1500000, status: 'active', aiGenerated: false },
      { title: 'Chemical Laboratory', description: 'Research chemistry laboratory with fume hoods, chemical storage, safety showers, and analytical instruments.', environmentType: 'Laboratory', setting: 'Indoor', lighting: 'Bright fluorescent with fume hood lighting', interactiveElements: ['Fume hoods', 'Safety shower', 'Eye wash station', 'Chemical storage', 'Lab instruments'], complexity: 'high', polyCount: 2200000, status: 'active', aiGenerated: false },
      { title: 'Underground Mine Tunnel', description: 'Realistic underground mine with tunnel systems, ventilation shafts, and mining equipment.', environmentType: 'Mining', setting: 'Underground', lighting: 'Helmet lights and tunnel fixtures', interactiveElements: ['Mining carts', 'Ventilation controls', 'Support structures', 'Emergency shelters', 'Communication systems'], complexity: 'high', polyCount: 2000000, status: 'active', aiGenerated: false },
      { title: 'Airport Terminal', description: 'International airport terminal with gates, security checkpoints, baggage claim, and customer service areas.', environmentType: 'Transportation', setting: 'Indoor', lighting: 'Natural skylights with commercial lighting', interactiveElements: ['Check-in kiosks', 'Gate displays', 'Security scanners', 'Baggage carousels', 'Information desks'], complexity: 'high', polyCount: 3500000, status: 'active', aiGenerated: false },
      { title: 'Restaurant Kitchen', description: 'Professional commercial kitchen with cooking stations, walk-in coolers, and food prep areas.', environmentType: 'Food Service', setting: 'Indoor', lighting: 'Bright task lighting', interactiveElements: ['Cooking equipment', 'Fire suppression', 'Refrigeration units', 'Prep stations', 'Dishwashing area'], complexity: 'medium', polyCount: 1600000, status: 'active', aiGenerated: false },
      { title: 'Warehouse Distribution Center', description: 'Large-scale warehouse with racking systems, loading docks, and material handling equipment.', environmentType: 'Logistics', setting: 'Indoor', lighting: 'High-bay industrial lighting', interactiveElements: ['Forklifts', 'Pallet racks', 'Loading docks', 'Conveyor systems', 'Inventory scanners'], complexity: 'medium', polyCount: 1900000, status: 'active', aiGenerated: false },
      { title: 'Electrical Substation', description: 'High-voltage electrical substation with transformers, switchgear, and control rooms.', environmentType: 'Energy', setting: 'Outdoor', lighting: 'Natural daylight', interactiveElements: ['Switchgear panels', 'Transformers', 'Control room consoles', 'Safety barriers', 'Grounding equipment'], complexity: 'medium', polyCount: 1200000, status: 'active', aiGenerated: false },
      { title: 'Emergency Room Department', description: 'Hospital emergency department with triage area, treatment bays, trauma room, and waiting area.', environmentType: 'Medical', setting: 'Indoor', lighting: 'Bright clinical lighting', interactiveElements: ['Patient monitors', 'Crash carts', 'Triage desk', 'Medical supplies', 'Communication systems'], complexity: 'high', polyCount: 2700000, status: 'active', aiGenerated: false },
      { title: 'Oil Refinery Platform', description: 'Offshore oil platform with processing equipment, living quarters, and helipad for industrial training.', environmentType: 'Oil & Gas', setting: 'Offshore', lighting: 'Natural with industrial task lighting', interactiveElements: ['Processing valves', 'Control panels', 'Safety systems', 'Helipad', 'Lifeboat stations'], complexity: 'high', polyCount: 3200000, status: 'active', aiGenerated: false },
      { title: 'Classroom Training Center', description: 'Modern training center with lecture hall, breakout rooms, and interactive display systems.', environmentType: 'Education', setting: 'Indoor', lighting: 'Adjustable ambient and presentation lighting', interactiveElements: ['Interactive whiteboards', 'Projector screens', 'Breakout areas', 'VR headset stations', 'Assessment terminals'], complexity: 'low', polyCount: 800000, status: 'active', aiGenerated: false },
      { title: 'Automotive Service Bay', description: 'Full automotive service facility with vehicle lifts, diagnostic equipment, and parts storage.', environmentType: 'Automotive', setting: 'Indoor', lighting: 'High-bay fluorescent with task lighting', interactiveElements: ['Vehicle lifts', 'Diagnostic computers', 'Tool chests', 'Parts counter', 'Tire equipment'], complexity: 'medium', polyCount: 1700000, status: 'active', aiGenerated: false },
    ]);
    console.log('VR Environment Templates seeded.');

    // 5. Incident Reports (15)
    await IncidentReport.bulkCreate([
      { title: 'Slip and Fall in Warehouse', description: 'Employee slipped on wet floor near loading dock area, resulting in sprained ankle.', incidentType: 'Slip/Fall', severity: 'moderate', location: 'Warehouse Loading Dock B', date: '2025-11-15', rootCause: 'Water leak from forklift radiator not cleaned up promptly', correctiveActions: ['Install drip trays under parked forklifts', 'Increase floor inspection frequency', 'Place anti-slip mats at dock entries', 'Repair forklift radiator'], status: 'resolved', aiAnalyzed: false },
      { title: 'Chemical Splash Eye Injury', description: 'Lab technician suffered chemical splash to eyes while transferring sulfuric acid without goggles.', incidentType: 'Chemical Exposure', severity: 'high', location: 'Chemistry Lab Room 204', date: '2025-10-22', rootCause: 'Employee bypassed PPE requirement due to time pressure', correctiveActions: ['Mandatory PPE compliance audit', 'Install splash guards on transfer stations', 'Retrain all lab personnel on PPE protocols', 'Install chemical-resistant face shields'], status: 'resolved', aiAnalyzed: false },
      { title: 'Forklift Near Miss', description: 'Forklift nearly struck pedestrian who entered aisle without checking for traffic.', incidentType: 'Near Miss', severity: 'high', location: 'Warehouse Aisle 7', date: '2025-12-03', rootCause: 'Inadequate pedestrian-vehicle separation and missing warning mirrors', correctiveActions: ['Install convex mirrors at aisle intersections', 'Paint pedestrian walkways', 'Add audible warning on forklifts', 'Implement traffic management plan'], status: 'open', aiAnalyzed: false },
      { title: 'Electrical Arc Flash Incident', description: 'Maintenance worker experienced arc flash while working on energized panel without proper procedures.', incidentType: 'Electrical', severity: 'critical', location: 'Main Electrical Room Building C', date: '2025-09-18', rootCause: 'Lockout/tagout procedure not followed, panel was energized during maintenance', correctiveActions: ['Retrain all electricians on LOTO procedures', 'Install arc flash labels on all panels', 'Require buddy system for electrical work', 'Upgrade PPE to arc-rated gear'], status: 'resolved', aiAnalyzed: true },
      { title: 'Repetitive Strain Injury Report', description: 'Assembly line worker developed carpal tunnel syndrome from repetitive wrist motions over six months.', incidentType: 'Ergonomic', severity: 'moderate', location: 'Assembly Line Station 12', date: '2025-11-01', rootCause: 'Workstation design forced sustained awkward wrist posture during assembly tasks', correctiveActions: ['Redesign workstation for neutral wrist position', 'Implement job rotation schedule', 'Provide ergonomic tools', 'Establish stretch break program'], status: 'open', aiAnalyzed: false },
      { title: 'Scaffold Collapse', description: 'Section of scaffolding collapsed during high wind event, fortunately no workers were on it at the time.', incidentType: 'Structural Failure', severity: 'critical', location: 'Building Exterior North Side', date: '2025-08-25', rootCause: 'Scaffold not properly braced for wind loading, missing cross braces on upper sections', correctiveActions: ['Implement wind speed monitoring system', 'Require daily scaffold inspections', 'Retrain scaffold erectors on bracing requirements', 'Establish wind speed work limits'], status: 'resolved', aiAnalyzed: true },
      { title: 'Heat Exhaustion Case', description: 'Outdoor construction worker suffered heat exhaustion during summer concrete pour in 98F weather.', incidentType: 'Environmental', severity: 'moderate', location: 'South Parking Lot Construction', date: '2025-07-14', rootCause: 'Inadequate hydration breaks and no shade structures provided for outdoor workers', correctiveActions: ['Implement mandatory hydration schedule', 'Provide shade structures on all outdoor sites', 'Train supervisors on heat illness recognition', 'Establish heat index work-rest cycles'], status: 'resolved', aiAnalyzed: false },
      { title: 'Caught-in Machine Incident', description: 'Worker caught loose clothing in rotating shaft of packaging machine, resulting in minor abrasion.', incidentType: 'Machine Related', severity: 'moderate', location: 'Packaging Department Machine P-4', date: '2025-10-09', rootCause: 'Machine guard was removed for maintenance and not reinstalled before operation resumed', correctiveActions: ['Install guard interlock switches', 'Prohibit loose clothing near machinery', 'Require guard verification before startup', 'Add machine guard checklist to pre-shift inspection'], status: 'resolved', aiAnalyzed: false },
      { title: 'Compressed Gas Cylinder Fall', description: 'Unsecured gas cylinder fell from storage rack, valve broke causing cylinder to become projectile.', incidentType: 'Falling Object', severity: 'critical', location: 'Welding Shop Storage Area', date: '2025-09-30', rootCause: 'Cylinder chains not properly secured, storage rack overcrowded beyond capacity', correctiveActions: ['Replace chains with cylinder clamps', 'Enforce storage capacity limits', 'Install cylinder cage storage', 'Conduct weekly cylinder storage audits'], status: 'open', aiAnalyzed: false },
      { title: 'Vehicle Backing Accident', description: 'Delivery truck backed into employee vehicle in parking lot while reversing without a spotter.', incidentType: 'Vehicle', severity: 'low', location: 'Employee Parking Lot East', date: '2025-11-28', rootCause: 'No spotter used for backing maneuver, backup camera obstructed by mud', correctiveActions: ['Require spotters for all backing maneuvers', 'Install backup cameras on all fleet vehicles', 'Redesign parking lot traffic flow', 'Clean cameras during pre-trip inspections'], status: 'resolved', aiAnalyzed: false },
      { title: 'Confined Space Oxygen Deficiency', description: 'Worker experienced dizziness entering a tank that had not been properly ventilated and tested.', incidentType: 'Confined Space', severity: 'high', location: 'Chemical Storage Tank T-3', date: '2025-10-17', rootCause: 'Atmospheric testing was not performed before entry, ventilation fan was not operating', correctiveActions: ['Enforce mandatory atmospheric testing', 'Install permanent ventilation systems', 'Require rescue team on standby', 'Retrain all confined space entrants'], status: 'resolved', aiAnalyzed: true },
      { title: 'Fire in Break Room', description: 'Small fire started from unattended toaster oven in employee break room, quickly extinguished.', incidentType: 'Fire', severity: 'moderate', location: 'Building A Break Room 2nd Floor', date: '2025-12-10', rootCause: 'Food left unattended in toaster oven, appliance had faulty auto-shutoff', correctiveActions: ['Replace all break room appliances with auto-shutoff models', 'Post appliance usage guidelines', 'Install smoke detectors in break rooms', 'Conduct fire extinguisher training'], status: 'resolved', aiAnalyzed: false },
      { title: 'Crane Load Drop', description: 'Crane dropped a steel beam from 20 feet due to rigging failure, no injuries but significant property damage.', incidentType: 'Rigging Failure', severity: 'critical', location: 'Steel Erection Area Grid C-5', date: '2025-08-12', rootCause: 'Worn sling used beyond its rated capacity, pre-use inspection not performed', correctiveActions: ['Implement sling inspection and retirement program', 'Require lift plans for all critical lifts', 'Train riggers on load calculations', 'Establish exclusion zones during lifts'], status: 'resolved', aiAnalyzed: true },
      { title: 'Noise-Induced Hearing Threshold Shift', description: 'Annual audiogram revealed temporary threshold shift in worker exposed to grinding operations.', incidentType: 'Noise Exposure', severity: 'moderate', location: 'Metal Fabrication Shop', date: '2025-11-05', rootCause: 'Hearing protection not worn consistently in high-noise areas exceeding 90 dBA', correctiveActions: ['Enforce mandatory hearing protection zones', 'Install engineering noise controls on grinders', 'Increase audiometric testing frequency', 'Provide custom-fit hearing protection'], status: 'open', aiAnalyzed: false },
      { title: 'Biological Exposure Needlestick', description: 'Nurse sustained needlestick injury while recapping a used hypodermic needle after patient blood draw.', incidentType: 'Biological', severity: 'high', location: 'Patient Care Unit 3 West', date: '2025-10-25', rootCause: 'Employee recapped needle manually instead of using safety-engineered device', correctiveActions: ['Replace all needles with safety-engineered devices', 'Retrain staff on sharps safety', 'Increase sharps container availability', 'Implement no-recap policy enforcement'], status: 'resolved', aiAnalyzed: false },
    ]);
    console.log('Incident Reports seeded.');

    // 6. Assessment Questions (15)
    await AssessmentQuestion.bulkCreate([
      { title: 'Fall Protection Height Threshold', question: 'At what height does OSHA require fall protection in the construction industry?', questionType: 'multiple-choice', category: 'Safety', difficulty: 'beginner', options: ['4 feet', '6 feet', '10 feet', '15 feet'], correctAnswer: '6 feet', explanation: 'OSHA standard 1926.501 requires fall protection at 6 feet in construction. General industry requires it at 4 feet.', points: 10, aiGenerated: false },
      { title: 'Fire Extinguisher Types', question: 'Which type of fire extinguisher should be used on an electrical fire?', questionType: 'multiple-choice', category: 'Fire Safety', difficulty: 'beginner', options: ['Class A - Water', 'Class B - Foam', 'Class C - CO2', 'Class D - Dry Powder'], correctAnswer: 'Class C - CO2', explanation: 'Class C extinguishers are rated for electrical fires. CO2 extinguishers are non-conductive and leave no residue.', points: 10, aiGenerated: false },
      { title: 'Lockout/Tagout Purpose', question: 'What is the primary purpose of Lockout/Tagout (LOTO) procedures?', questionType: 'multiple-choice', category: 'Safety', difficulty: 'beginner', options: ['To identify equipment needing repair', 'To prevent unexpected startup of machinery during maintenance', 'To track equipment usage hours', 'To schedule preventive maintenance'], correctAnswer: 'To prevent unexpected startup of machinery during maintenance', explanation: 'LOTO procedures ensure that machines are properly shut off and cannot be started during maintenance or servicing.', points: 10, aiGenerated: false },
      { title: 'Sterile Field Contamination', question: 'Which action would break sterile technique in the operating room?', questionType: 'multiple-choice', category: 'Surgical Safety', difficulty: 'intermediate', options: ['Keeping sterile items above waist level', 'Opening sterile packages away from the field', 'Reaching across a sterile field', 'Using sterile gloves to handle sterile items'], correctAnswer: 'Reaching across a sterile field', explanation: 'Reaching across a sterile field can introduce contamination from non-sterile areas of the body or clothing.', points: 15, aiGenerated: false },
      { title: 'Customer De-escalation Technique', question: 'What is the most effective first step when dealing with an angry customer?', questionType: 'multiple-choice', category: 'Customer Service', difficulty: 'intermediate', options: ['Immediately offer a discount', 'Ask them to calm down', 'Actively listen and acknowledge their frustration', 'Transfer to a manager'], correctAnswer: 'Actively listen and acknowledge their frustration', explanation: 'Active listening and acknowledgment validates the customer feelings and begins building rapport before problem-solving.', points: 15, aiGenerated: false },
      { title: 'VR Motion Sickness Prevention', question: 'Which frame rate is generally considered the minimum to prevent VR motion sickness?', questionType: 'multiple-choice', category: 'VR Design', difficulty: 'intermediate', options: ['30 FPS', '60 FPS', '90 FPS', '120 FPS'], correctAnswer: '90 FPS', explanation: 'Most VR platforms target 90 FPS as the minimum to reduce motion sickness. Lower frame rates can cause discomfort.', points: 15, aiGenerated: false },
      { title: 'Hazard Communication Labels', question: 'Under GHS, what does a skull and crossbones pictogram indicate?', questionType: 'multiple-choice', category: 'Chemical Safety', difficulty: 'beginner', options: ['Flammable material', 'Acute toxicity', 'Corrosive material', 'Environmental hazard'], correctAnswer: 'Acute toxicity', explanation: 'The skull and crossbones pictogram under GHS indicates acute toxicity - materials that can cause death or serious harm with short exposure.', points: 10, aiGenerated: false },
      { title: 'Incident Investigation Root Cause', question: 'Which analysis method uses a fishbone diagram to identify root causes of incidents?', questionType: 'multiple-choice', category: 'Incident Analysis', difficulty: 'intermediate', options: ['Fault Tree Analysis', 'Ishikawa (Cause and Effect) Analysis', 'Bow Tie Analysis', 'Swiss Cheese Model'], correctAnswer: 'Ishikawa (Cause and Effect) Analysis', explanation: 'The Ishikawa or fishbone diagram organizes potential causes into categories like People, Process, Equipment, and Environment.', points: 15, aiGenerated: false },
      { title: 'CPR Compression Rate', question: 'What is the recommended chest compression rate for adult CPR?', questionType: 'multiple-choice', category: 'Emergency Response', difficulty: 'beginner', options: ['60-80 per minute', '80-100 per minute', '100-120 per minute', '120-140 per minute'], correctAnswer: '100-120 per minute', explanation: 'Current AHA guidelines recommend a compression rate of 100-120 per minute for adult CPR.', points: 10, aiGenerated: false },
      { title: 'Ergonomic Monitor Placement', question: 'What is the recommended distance between a computer monitor and the user eyes?', questionType: 'multiple-choice', category: 'Ergonomics', difficulty: 'beginner', options: ['12-18 inches', '20-26 inches', '30-36 inches', '40-48 inches'], correctAnswer: '20-26 inches', explanation: 'The monitor should be approximately an arm length away (20-26 inches) with the top of the screen at or slightly below eye level.', points: 10, aiGenerated: false },
      { title: 'Surgical Timeout Purpose', question: 'What is the primary purpose of a surgical timeout?', questionType: 'multiple-choice', category: 'Surgical Safety', difficulty: 'intermediate', options: ['To allow the surgeon to rest', 'To verify correct patient, procedure, and site', 'To sterilize the operating room', 'To count surgical instruments'], correctAnswer: 'To verify correct patient, procedure, and site', explanation: 'The surgical timeout is a mandatory pause before the procedure to confirm patient identity, planned procedure, and correct surgical site.', points: 15, aiGenerated: false },
      { title: 'Compliance Training Frequency', question: 'How often does OSHA require Hazard Communication training to be updated?', questionType: 'multiple-choice', category: 'Compliance', difficulty: 'intermediate', options: ['Annually', 'Every 2 years', 'When new hazards are introduced', 'Every 5 years'], correctAnswer: 'When new hazards are introduced', explanation: 'OSHA requires HazCom training whenever a new chemical hazard is introduced to the workplace, not on a fixed schedule.', points: 15, aiGenerated: false },
      { title: 'VR Haptic Feedback Purpose', question: 'What is the primary benefit of haptic feedback in VR training simulations?', questionType: 'multiple-choice', category: 'VR Technology', difficulty: 'advanced', options: ['Reduces rendering load', 'Provides tactile sensation to enhance realism', 'Improves audio quality', 'Reduces file size'], correctAnswer: 'Provides tactile sensation to enhance realism', explanation: 'Haptic feedback simulates touch and physical sensation, making VR training more realistic and improving skill transfer to real-world tasks.', points: 20, aiGenerated: false },
      { title: 'Blood Spill Cleanup Protocol', question: 'What concentration of bleach solution is recommended for cleaning blood spills?', questionType: 'multiple-choice', category: 'Biosafety', difficulty: 'advanced', options: ['1:1 ratio', '1:10 ratio', '1:100 ratio', '1:1000 ratio'], correctAnswer: '1:10 ratio', explanation: 'A 1:10 dilution of sodium hypochlorite (bleach) is the standard for decontaminating blood spills, providing effective pathogen kill.', points: 20, aiGenerated: false },
      { title: 'Emergency Action Plan Components', question: 'Which is NOT a required element of an OSHA Emergency Action Plan?', questionType: 'multiple-choice', category: 'Emergency Preparedness', difficulty: 'advanced', options: ['Evacuation procedures and routes', 'Procedures for employees who remain to perform critical operations', 'List of all employee personal phone numbers', 'Means of reporting emergencies'], correctAnswer: 'List of all employee personal phone numbers', explanation: 'OSHA 1910.38 requires evacuation procedures, critical operation procedures, emergency reporting means, and contact info for plan details, but not personal phone lists.', points: 20, aiGenerated: false },
    ]);
    console.log('Assessment Questions seeded.');

    // 7. Assessment Scores (15)
    await AssessmentScore.bulkCreate([
      { traineeEmail: 'john.smith@company.com', traineeName: 'John Smith', moduleName: 'Fall Protection Safety', score: 85, maxScore: 100, percentage: 85, attemptDate: '2025-11-20', timeSpent: 1800, passed: true, feedback: 'Strong understanding of fall protection principles. Review harness inspection procedures.' },
      { traineeEmail: 'sarah.johnson@company.com', traineeName: 'Sarah Johnson', moduleName: 'Chemical Safety Handling', score: 92, maxScore: 100, percentage: 92, attemptDate: '2025-11-18', timeSpent: 2100, passed: true, feedback: 'Excellent performance. Demonstrated thorough knowledge of MSDS interpretation.' },
      { traineeEmail: 'mike.williams@company.com', traineeName: 'Mike Williams', moduleName: 'Fire Safety and Evacuation', score: 68, maxScore: 100, percentage: 68, passed: false, attemptDate: '2025-11-15', timeSpent: 1500, feedback: 'Needs improvement on evacuation route knowledge. Schedule retake in 2 weeks.' },
      { traineeEmail: 'emily.brown@company.com', traineeName: 'Emily Brown', moduleName: 'Surgical Sterile Technique', score: 95, maxScore: 100, percentage: 95, attemptDate: '2025-11-22', timeSpent: 2400, passed: true, feedback: 'Outstanding performance. Perfect score on contamination prevention scenarios.' },
      { traineeEmail: 'david.garcia@company.com', traineeName: 'David Garcia', moduleName: 'Forklift Operation', score: 78, maxScore: 100, percentage: 78, attemptDate: '2025-11-10', timeSpent: 1950, passed: true, feedback: 'Passed with adequate knowledge. Focus on load capacity calculations for improvement.' },
      { traineeEmail: 'lisa.martinez@company.com', traineeName: 'Lisa Martinez', moduleName: 'Customer Service Excellence', score: 88, maxScore: 100, percentage: 88, attemptDate: '2025-11-25', timeSpent: 2200, passed: true, feedback: 'Very good de-escalation skills. Could improve on technical product knowledge.' },
      { traineeEmail: 'james.anderson@company.com', traineeName: 'James Anderson', moduleName: 'Lockout/Tagout Procedures', score: 45, maxScore: 100, percentage: 45, attemptDate: '2025-11-08', timeSpent: 1200, passed: false, feedback: 'Failed assessment. Must complete full LOTO retraining before retake.' },
      { traineeEmail: 'jennifer.taylor@company.com', traineeName: 'Jennifer Taylor', moduleName: 'Emergency Response Basics', score: 91, maxScore: 100, percentage: 91, attemptDate: '2025-11-28', timeSpent: 1700, passed: true, feedback: 'Excellent CPR and first aid knowledge. Strong performance on triage scenarios.' },
      { traineeEmail: 'robert.thomas@company.com', traineeName: 'Robert Thomas', moduleName: 'Confined Space Entry', score: 82, maxScore: 100, percentage: 82, attemptDate: '2025-11-12', timeSpent: 2500, passed: true, feedback: 'Good understanding of atmospheric testing. Review rescue procedures for higher score.' },
      { traineeEmail: 'maria.hernandez@company.com', traineeName: 'Maria Hernandez', moduleName: 'Bloodborne Pathogen Safety', score: 97, maxScore: 100, percentage: 97, attemptDate: '2025-11-30', timeSpent: 1600, passed: true, feedback: 'Near perfect score. Demonstrated expert-level knowledge of exposure control plans.' },
      { traineeEmail: 'william.jones@company.com', traineeName: 'William Jones', moduleName: 'Electrical Safety', score: 73, maxScore: 100, percentage: 73, attemptDate: '2025-11-05', timeSpent: 2000, passed: true, feedback: 'Passed but needs improvement on arc flash calculations and boundary distances.' },
      { traineeEmail: 'patricia.davis@company.com', traineeName: 'Patricia Davis', moduleName: 'Ergonomic Workplace Setup', score: 86, maxScore: 100, percentage: 86, attemptDate: '2025-12-01', timeSpent: 1300, passed: true, feedback: 'Good knowledge of workstation ergonomics. Excellent understanding of break scheduling.' },
      { traineeEmail: 'michael.wilson@company.com', traineeName: 'Michael Wilson', moduleName: 'Hazardous Materials Handling', score: 59, maxScore: 100, percentage: 59, attemptDate: '2025-11-14', timeSpent: 2300, passed: false, feedback: 'Did not pass. Significant gaps in DOT classification knowledge. Full retraining required.' },
      { traineeEmail: 'susan.moore@company.com', traineeName: 'Susan Moore', moduleName: 'VR Equipment Operation', score: 90, maxScore: 100, percentage: 90, attemptDate: '2025-12-05', timeSpent: 1400, passed: true, feedback: 'Excellent technical skills with VR equipment. Good understanding of calibration procedures.' },
      { traineeEmail: 'daniel.jackson@company.com', traineeName: 'Daniel Jackson', moduleName: 'Incident Investigation Methods', score: 84, maxScore: 100, percentage: 84, attemptDate: '2025-12-08', timeSpent: 2600, passed: true, feedback: 'Strong root cause analysis skills. Could improve on corrective action prioritization.' },
    ]);
    console.log('Assessment Scores seeded.');

    // 8. Compliance Requirements (15)
    await ComplianceRequirement.bulkCreate([
      { title: 'OSHA Hazard Communication Standard', description: 'Compliance with OSHA 29 CFR 1910.1200 requiring chemical hazard information and training.', regulationType: 'Federal', authority: 'OSHA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['Manufacturing', 'Laboratory', 'Maintenance'], lastAuditDate: '2025-06-15' },
      { title: 'HIPAA Privacy Rule', description: 'Compliance with Health Insurance Portability and Accountability Act for patient data protection.', regulationType: 'Federal', authority: 'HHS', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'critical', applicableDepartments: ['Healthcare', 'IT', 'Administration'], lastAuditDate: '2025-09-20' },
      { title: 'Fire Safety Code Compliance', description: 'Compliance with NFPA 101 Life Safety Code for building fire protection and evacuation.', regulationType: 'National', authority: 'NFPA', effectiveDate: '2024-03-01', expiryDate: '2027-03-01', status: 'active', priority: 'high', applicableDepartments: ['Facilities', 'Safety', 'All Departments'], lastAuditDate: '2025-08-10' },
      { title: 'EPA Waste Management Regulations', description: 'Compliance with RCRA for proper handling, storage, and disposal of hazardous waste.', regulationType: 'Federal', authority: 'EPA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['Environmental', 'Manufacturing', 'Laboratory'], lastAuditDate: '2025-05-22' },
      { title: 'ADA Accessibility Requirements', description: 'Compliance with Americans with Disabilities Act for workplace accessibility and accommodations.', regulationType: 'Federal', authority: 'DOJ', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'medium', applicableDepartments: ['HR', 'Facilities', 'All Departments'], lastAuditDate: '2025-04-18' },
      { title: 'DOT Hazmat Transportation', description: 'Compliance with DOT 49 CFR for safe transportation of hazardous materials.', regulationType: 'Federal', authority: 'DOT', effectiveDate: '2024-06-01', expiryDate: '2027-06-01', status: 'active', priority: 'high', applicableDepartments: ['Logistics', 'Shipping', 'Warehouse'], lastAuditDate: '2025-07-30' },
      { title: 'OSHA Respiratory Protection', description: 'Compliance with 29 CFR 1910.134 for respiratory protection program requirements.', regulationType: 'Federal', authority: 'OSHA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['Manufacturing', 'Maintenance', 'Construction'], lastAuditDate: '2025-03-12' },
      { title: 'Joint Commission Standards', description: 'Accreditation standards for healthcare organizations covering patient safety and quality.', regulationType: 'Accreditation', authority: 'Joint Commission', effectiveDate: '2024-01-01', expiryDate: '2027-01-01', status: 'active', priority: 'critical', applicableDepartments: ['Healthcare', 'Nursing', 'Pharmacy'], lastAuditDate: '2025-10-05' },
      { title: 'GDPR Data Protection', description: 'European Union General Data Protection Regulation for handling personal data of EU residents.', regulationType: 'International', authority: 'EU Commission', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['IT', 'Marketing', 'HR', 'Legal'], lastAuditDate: '2025-08-28' },
      { title: 'ISO 45001 Occupational Health', description: 'International standard for occupational health and safety management systems.', regulationType: 'International', authority: 'ISO', effectiveDate: '2024-02-01', expiryDate: '2027-02-01', status: 'active', priority: 'medium', applicableDepartments: ['Safety', 'HR', 'Operations'], lastAuditDate: '2025-06-01' },
      { title: 'OSHA Bloodborne Pathogens', description: 'Compliance with 29 CFR 1910.1030 for occupational exposure to bloodborne pathogens.', regulationType: 'Federal', authority: 'OSHA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'critical', applicableDepartments: ['Healthcare', 'Emergency Services', 'Janitorial'], lastAuditDate: '2025-09-15' },
      { title: 'PCI DSS Payment Card Security', description: 'Payment Card Industry Data Security Standard for protecting cardholder data.', regulationType: 'Industry', authority: 'PCI Security Standards Council', effectiveDate: '2024-04-01', expiryDate: '2027-04-01', status: 'active', priority: 'high', applicableDepartments: ['IT', 'Finance', 'Retail Operations'], lastAuditDate: '2025-11-20' },
      { title: 'OSHA Permit-Required Confined Spaces', description: 'Compliance with 29 CFR 1910.146 for entry into permit-required confined spaces.', regulationType: 'Federal', authority: 'OSHA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['Maintenance', 'Construction', 'Utilities'], lastAuditDate: '2025-07-08' },
      { title: 'FDA Medical Device Regulations', description: 'FDA 21 CFR regulations for medical device manufacturing, testing, and labeling.', regulationType: 'Federal', authority: 'FDA', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'critical', applicableDepartments: ['Manufacturing', 'Quality', 'R&D'], lastAuditDate: '2025-10-30' },
      { title: 'State Workers Compensation Compliance', description: 'State-specific workers compensation insurance and reporting requirements.', regulationType: 'State', authority: 'State Labor Department', effectiveDate: '2024-01-01', expiryDate: '2026-12-31', status: 'active', priority: 'high', applicableDepartments: ['HR', 'Safety', 'Legal', 'Finance'], lastAuditDate: '2025-02-14' },
    ]);
    console.log('Compliance Requirements seeded.');

    // 9. Training Modules (15)
    await TrainingModule.bulkCreate([
      { title: 'Introduction to Workplace Safety', description: 'Foundational course covering general workplace safety principles, hazard recognition, and reporting procedures.', category: 'Safety', difficulty: 'beginner', duration: 60, prerequisites: [], learningObjectives: ['Identify common workplace hazards', 'Understand reporting procedures', 'Know emergency contacts', 'Recognize safety signage'], format: 'VR Interactive', maxParticipants: 20, status: 'active' },
      { title: 'Advanced Fire Safety and Suppression', description: 'In-depth training on fire prevention, suppression systems, and emergency evacuation leadership.', category: 'Fire Safety', difficulty: 'advanced', duration: 120, prerequisites: ['Introduction to Workplace Safety'], learningObjectives: ['Operate fire suppression systems', 'Lead evacuation procedures', 'Conduct fire risk assessments', 'Use all fire extinguisher types'], format: 'VR Simulation', maxParticipants: 10, status: 'active' },
      { title: 'Basic Surgical Instrument Handling', description: 'Introductory course on proper handling, passing, and identification of common surgical instruments.', category: 'Medical', difficulty: 'beginner', duration: 90, prerequisites: [], learningObjectives: ['Identify 30 common instruments', 'Demonstrate proper passing technique', 'Understand sterile field principles', 'Practice instrument counting'], format: 'VR Hands-on', maxParticipants: 8, status: 'active' },
      { title: 'Customer Conflict Resolution', description: 'Training on de-escalation techniques, empathetic communication, and creative problem solving for customer issues.', category: 'Customer Service', difficulty: 'intermediate', duration: 90, prerequisites: ['Customer Service Fundamentals'], learningObjectives: ['Apply de-escalation techniques', 'Practice empathetic listening', 'Develop creative solutions', 'Manage personal stress responses'], format: 'VR Roleplay', maxParticipants: 12, status: 'active' },
      { title: 'Hazardous Material Handling', description: 'Comprehensive training on identifying, handling, storing, and disposing of hazardous materials safely.', category: 'Safety', difficulty: 'intermediate', duration: 120, prerequisites: ['Introduction to Workplace Safety'], learningObjectives: ['Read SDS sheets', 'Select proper PPE', 'Follow spill procedures', 'Understand waste disposal regulations'], format: 'VR Interactive', maxParticipants: 15, status: 'active' },
      { title: 'VR Equipment Setup and Calibration', description: 'Technical training on setting up, calibrating, and maintaining VR training equipment.', category: 'Technical', difficulty: 'intermediate', duration: 60, prerequisites: [], learningObjectives: ['Set up VR headsets', 'Calibrate tracking systems', 'Troubleshoot common issues', 'Perform basic maintenance'], format: 'Hands-on Lab', maxParticipants: 10, status: 'active' },
      { title: 'Emergency Medical Response Level 1', description: 'Basic emergency medical response training covering CPR, AED use, and first aid essentials.', category: 'Emergency Response', difficulty: 'beginner', duration: 180, prerequisites: [], learningObjectives: ['Perform adult CPR', 'Operate an AED', 'Treat common injuries', 'Activate emergency response'], format: 'VR Simulation', maxParticipants: 12, status: 'active' },
      { title: 'Electrical Safety and LOTO', description: 'Training on electrical hazard recognition, safe work practices, and lockout/tagout procedures.', category: 'Safety', difficulty: 'intermediate', duration: 90, prerequisites: ['Introduction to Workplace Safety'], learningObjectives: ['Identify electrical hazards', 'Perform LOTO procedures', 'Select electrical PPE', 'Respond to electrical emergencies'], format: 'VR Interactive', maxParticipants: 10, status: 'active' },
      { title: 'Leadership in Safety Management', description: 'Advanced course for supervisors on building a safety culture, incident investigation, and regulatory compliance.', category: 'Leadership', difficulty: 'advanced', duration: 240, prerequisites: ['Introduction to Workplace Safety', 'Hazardous Material Handling'], learningObjectives: ['Conduct safety audits', 'Lead incident investigations', 'Build safety culture', 'Manage compliance programs'], format: 'Blended Learning', maxParticipants: 15, status: 'active' },
      { title: 'Ergonomics and Injury Prevention', description: 'Training on workplace ergonomics, proper body mechanics, and prevention of musculoskeletal disorders.', category: 'Health', difficulty: 'beginner', duration: 45, prerequisites: [], learningObjectives: ['Set up ergonomic workstation', 'Practice proper lifting', 'Recognize early injury signs', 'Implement stretch breaks'], format: 'VR Interactive', maxParticipants: 20, status: 'active' },
      { title: 'Confined Space Operations', description: 'Specialized training for working in permit-required confined spaces including atmospheric monitoring.', category: 'Safety', difficulty: 'advanced', duration: 180, prerequisites: ['Introduction to Workplace Safety', 'Hazardous Material Handling'], learningObjectives: ['Classify confined spaces', 'Perform atmospheric testing', 'Set up entry permits', 'Execute rescue procedures'], format: 'VR Simulation', maxParticipants: 8, status: 'active' },
      { title: 'Customer Service Fundamentals', description: 'Foundation course on customer service principles, communication skills, and company policies.', category: 'Customer Service', difficulty: 'beginner', duration: 60, prerequisites: [], learningObjectives: ['Understand service standards', 'Practice active listening', 'Navigate company policies', 'Handle basic inquiries'], format: 'VR Roleplay', maxParticipants: 15, status: 'active' },
      { title: 'Incident Report Writing', description: 'Training on documenting workplace incidents accurately, completely, and in compliance with regulations.', category: 'Compliance', difficulty: 'intermediate', duration: 60, prerequisites: ['Introduction to Workplace Safety'], learningObjectives: ['Document incident details', 'Identify contributing factors', 'Complete regulatory forms', 'Maintain chain of custody'], format: 'Workshop', maxParticipants: 20, status: 'active' },
      { title: 'Advanced Laparoscopic Skills', description: 'Advanced surgical skills training for laparoscopic procedures including suturing and tissue manipulation.', category: 'Medical', difficulty: 'advanced', duration: 240, prerequisites: ['Basic Surgical Instrument Handling'], learningObjectives: ['Master camera navigation', 'Perform intracorporeal suturing', 'Handle tissue safely', 'Manage complications'], format: 'VR Simulation', maxParticipants: 6, status: 'active' },
      { title: 'Radiation Safety for Healthcare', description: 'Training on radiation protection principles for healthcare workers in diagnostic and therapeutic settings.', category: 'Safety', difficulty: 'intermediate', duration: 90, prerequisites: [], learningObjectives: ['Apply ALARA principle', 'Use radiation monitoring devices', 'Select appropriate shielding', 'Handle radiation emergencies'], format: 'VR Interactive', maxParticipants: 12, status: 'active' },
    ]);
    console.log('Training Modules seeded.');

    // 10. Certification Records (15)
    await CertificationRecord.bulkCreate([
      { traineeName: 'John Smith', traineeEmail: 'john.smith@company.com', certificationName: 'OSHA 30-Hour Construction', issuingBody: 'OSHA Training Institute', issueDate: '2025-03-15', expiryDate: '2030-03-15', status: 'active', score: 92, certificateNumber: 'OSHA-30-2025-0415', renewalRequired: false },
      { traineeName: 'Sarah Johnson', traineeEmail: 'sarah.johnson@company.com', certificationName: 'Certified Safety Professional (CSP)', issuingBody: 'Board of Certified Safety Professionals', issueDate: '2025-01-10', expiryDate: '2030-01-10', status: 'active', score: 88, certificateNumber: 'CSP-2025-78432', renewalRequired: true },
      { traineeName: 'Mike Williams', traineeEmail: 'mike.williams@company.com', certificationName: 'Forklift Operator License', issuingBody: 'National Safety Council', issueDate: '2025-06-20', expiryDate: '2028-06-20', status: 'active', score: 85, certificateNumber: 'FKL-2025-11234', renewalRequired: true },
      { traineeName: 'Emily Brown', traineeEmail: 'emily.brown@company.com', certificationName: 'BLS Healthcare Provider', issuingBody: 'American Heart Association', issueDate: '2025-04-05', expiryDate: '2027-04-05', status: 'active', score: 96, certificateNumber: 'AHA-BLS-2025-55678', renewalRequired: true },
      { traineeName: 'David Garcia', traineeEmail: 'david.garcia@company.com', certificationName: 'Hazmat Technician Level', issuingBody: 'National Fire Protection Association', issueDate: '2024-11-30', expiryDate: '2025-11-30', status: 'expired', score: 79, certificateNumber: 'NFPA-HMT-2024-33210', renewalRequired: true },
      { traineeName: 'Lisa Martinez', traineeEmail: 'lisa.martinez@company.com', certificationName: 'Certified Customer Service Professional', issuingBody: 'Customer Service Institute', issueDate: '2025-08-12', expiryDate: '2028-08-12', status: 'active', score: 91, certificateNumber: 'CCSP-2025-44567', renewalRequired: true },
      { traineeName: 'James Anderson', traineeEmail: 'james.anderson@company.com', certificationName: 'Confined Space Rescue Technician', issuingBody: 'National Safety Council', issueDate: '2025-05-18', expiryDate: '2028-05-18', status: 'active', score: 87, certificateNumber: 'CSRT-2025-22890', renewalRequired: true },
      { traineeName: 'Jennifer Taylor', traineeEmail: 'jennifer.taylor@company.com', certificationName: 'ACLS Provider', issuingBody: 'American Heart Association', issueDate: '2025-02-28', expiryDate: '2027-02-28', status: 'active', score: 94, certificateNumber: 'AHA-ACLS-2025-99012', renewalRequired: true },
      { traineeName: 'Robert Thomas', traineeEmail: 'robert.thomas@company.com', certificationName: 'Certified Industrial Hygienist', issuingBody: 'American Board of Industrial Hygiene', issueDate: '2024-09-15', expiryDate: '2029-09-15', status: 'active', score: 83, certificateNumber: 'CIH-2024-67345', renewalRequired: true },
      { traineeName: 'Maria Hernandez', traineeEmail: 'maria.hernandez@company.com', certificationName: 'Infection Control Certificate', issuingBody: 'Certification Board of Infection Control', issueDate: '2025-07-01', expiryDate: '2030-07-01', status: 'active', score: 98, certificateNumber: 'CBIC-2025-10456', renewalRequired: true },
      { traineeName: 'William Jones', traineeEmail: 'william.jones@company.com', certificationName: 'NFPA 70E Electrical Safety', issuingBody: 'National Fire Protection Association', issueDate: '2025-03-22', expiryDate: '2028-03-22', status: 'active', score: 76, certificateNumber: 'NFPA70E-2025-88901', renewalRequired: true },
      { traineeName: 'Patricia Davis', traineeEmail: 'patricia.davis@company.com', certificationName: 'Certified Ergonomics Assessment Specialist', issuingBody: 'Board of Certification in Professional Ergonomics', issueDate: '2025-10-10', expiryDate: '2030-10-10', status: 'active', score: 89, certificateNumber: 'CEAS-2025-34567', renewalRequired: true },
      { traineeName: 'Michael Wilson', traineeEmail: 'michael.wilson@company.com', certificationName: 'DOT Hazmat Employee Training', issuingBody: 'Department of Transportation', issueDate: '2024-08-05', expiryDate: '2025-08-05', status: 'expired', score: 72, certificateNumber: 'DOT-HME-2024-56789', renewalRequired: true },
      { traineeName: 'Susan Moore', traineeEmail: 'susan.moore@company.com', certificationName: 'VR Development Professional', issuingBody: 'International VR Association', issueDate: '2025-09-01', expiryDate: '2028-09-01', status: 'active', score: 93, certificateNumber: 'IVRA-VDP-2025-12345', renewalRequired: true },
      { traineeName: 'Daniel Jackson', traineeEmail: 'daniel.jackson@company.com', certificationName: 'Root Cause Analysis Practitioner', issuingBody: 'TapRooT Training', issueDate: '2025-06-15', expiryDate: '2028-06-15', status: 'active', score: 86, certificateNumber: 'RCA-2025-78901', renewalRequired: true },
    ]);
    console.log('Certification Records seeded.');

    console.log('\nAll seed data inserted successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seeding failed:', err);
    process.exit(1);
  }
}

seed();
